my_message=ds_grid_create(10,5)

ds_grid_add(my_message,0,0,"Test NPC, có vẻ là khá ổn rồi, ko có lỗi")
ds_grid_add(my_message,0,1,2)
ds_grid_add(my_message,0,2,0)
ds_grid_add(my_message,0,3,sp_Tuesday)
ds_grid_add(my_message,0,4,sp_Boy)

ds_grid_add(my_message,1,0,"À , Tôi sẽ giải thích cơ chế hoạt động của NPC. Bình thường là click vào npc thì dòng chat xuất hiện đúng ko")
ds_grid_add(my_message,1,1,2)
ds_grid_add(my_message,1,2,0)
ds_grid_add(my_message,1,3,sp_Tuesday)
ds_grid_add(my_message,1,4,sp_Boy)

ds_grid_add(my_message,2,0,"Cái ds grid của npc sẽ thay thế ds grid của cái BoxText")
ds_grid_add(my_message,2,1,2)
ds_grid_add(my_message,2,2,0)
ds_grid_add(my_message,2,3,sp_Tuesday)
ds_grid_add(my_message,2,4,sp_Boy)

ds_grid_add(my_message,3,0,"Sau khi đã thay thế ds grid thành ds grid của NPC thì ds ban đầu sẽ biến mất")
ds_grid_add(my_message,3,1,2)
ds_grid_add(my_message,3,2,0)
ds_grid_add(my_message,3,3,sp_Tuesday)
ds_grid_add(my_message,3,4,sp_Boy)

ds_grid_add(my_message,4,0,"Vì vậy nên cái text lúc đầu í, tôi sẽ ko cho hình ảnh và chỉ là vài dòng text giới thiệu game thôi")
ds_grid_add(my_message,4,1,2)
ds_grid_add(my_message,4,2,0)
ds_grid_add(my_message,4,3,sp_Tuesday)
ds_grid_add(my_message,4,4,sp_Boy)

ds_grid_add(my_message,5,0,"À có 1 điều cần lưu í với ông, Đừng viết bất cứ 1 chữ nào quá dài, ví dụ ahhhhhhhhhhhhhhhhhhhhhhhhjhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh")
ds_grid_add(my_message,5,1,2)
ds_grid_add(my_message,5,2,0)
ds_grid_add(my_message,5,3,sp_Tuesday)
ds_grid_add(my_message,5,4,sp_Boy)

ds_grid_add(my_message,6,0,"Đó, nó sẽ bị vượt qua width")
ds_grid_add(my_message,6,1,2)
ds_grid_add(my_message,6,2,0)
ds_grid_add(my_message,6,3,sp_Tuesday)
ds_grid_add(my_message,6,4,sp_Boy)

ds_grid_add(my_message,7,0,"Bây giờ tôi sẽ thử ko có hình ảnh để làm text game lúc mới vào")
ds_grid_add(my_message,7,1,2)
ds_grid_add(my_message,7,2,-1)
ds_grid_add(my_message,7,3,0)
ds_grid_add(my_message,7,4,0)

ds_grid_add(my_message,8,0,"Đc rồi, ông chỉ cần set trục y khi y=2 của cái ds grid thành -1 là ok")
ds_grid_add(my_message,8,1,2)
ds_grid_add(my_message,8,2,-1)
ds_grid_add(my_message,7,3,0)
ds_grid_add(my_message,8,4,0)